import { HomeTemplate } from '../lib/templates/home/home-template';
import Head from 'next/head';

export default function Home() {
   return (
      <div>
         <Head>
            <title>Test - Ciomprix</title>
            <meta charSet='utf-8' />
            <meta name='viewport' content='initial-scale=1.0, width=device-width' />
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <HomeTemplate />
      </div>
   );
}
