import { UsersTemplate } from '../../lib/templates/users/users-template';
import Head from 'next/head';

export default function Profile() {
   return (
      <div>
         <Head>
            <title>Test - Ciomprix</title>
            <meta charSet='utf-8' />
            <meta name='viewport' content='initial-scale=1.0, width=device-width' />
            <meta name='description' content='Generated by create next app' />
            <meta httpEquiv='Content-Security-Policy' content='Content-Security-Policy' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <UsersTemplate />
      </div>
   );
}
